### ISSUE TITLE
1.0.2 is not compatible with GWT 2.10.0

### ISSUE THREAD

**Issue by dnouls** [google/jsinterop-annotations#5]
According to the documentation we should use version 1.0.2 in combination with GWT 2.10.0, but this gave me a lot of errors about @JsNonNull not being found.

I switched to 2.0.1 and now my project is compiling.

Is the documentation outdated or is GWT 2.10.0 depending on an annotation that it shouldn't ?

**Comment by gkdn** [comment]
It might be coming from JRE though they don't do anything.

Could you post some example errors?

Also @niloc132

**Comment by niloc132** [comment]
GWT versions 2.9.0, 2.10.0 require (and ship with) jsinterop-annotations 2.0.0. See the [release notes mention for 2.9.0](https://www.gwtproject.org/release-notes.html#Release_Notes_2_9_0).

For maven, you get this from the gwt pom itself https://search.maven.org/artifact/org.gwtproject/gwt/2.10.0/jar

Downloading the gwt SDK zip file, it is included automatically in that copy of gwt-user.jar:
```bash
[colin@wrangler gwt-2.10.0]$ unzip -l gwt-2.10.0/gwt-user.jar  | grep jsinterop
        0  2022-06-02 14:19   jsinterop/
        0  2022-06-02 14:19   jsinterop/annotations/
      429  2010-01-01 00:00   jsinterop/annotations/JsAsync.class
      446  2010-01-01 00:00   jsinterop/annotations/JsConstructor.class
      603  2010-01-01 00:00   jsinterop/annotations/JsEnum.class
      433  2010-01-01 00:00   jsinterop/annotations/JsFunction.class
      463  2010-01-01 00:00   jsinterop/annotations/JsIgnore.class
      536  2010-01-01 00:00   jsinterop/annotations/JsMethod.class
      435  2010-01-01 00:00   jsinterop/annotations/JsNonNull.class
      437  2010-01-01 00:00   jsinterop/annotations/JsNullable.class
      438  2010-01-01 00:00   jsinterop/annotations/JsOptional.class
      446  2010-01-01 00:00   jsinterop/annotations/JsOverlay.class
      553  2010-01-01 00:00   jsinterop/annotations/JsPackage.class
      553  2010-01-01 00:00   jsinterop/annotations/JsProperty.class
      569  2010-01-01 00:00   jsinterop/annotations/JsType.class
```


Where did you find documentation indicating that 1.0.2 is preferred?

**Comment by dnouls** [comment]
Sorry, I was indeed confused. I always mix Elemental and JsInterop.

But anyway, maybe I overlooked but I did not even find a mention on how to use GWT with maven.

It would be nice if the gwtproject site would at least contain a section on how to do that. I am assuming that most people use maven or gradle over ant these days. If you search the internet for how to do it many examples are still using the old gwt maven plugin, while tbroyer's plugin is much better for example.

**Comment by dnouls** [comment]
What actually confused me is that the jsinterop documentation is mentioning that GWT devs should stick with 1.0.2
https://github.com/google/jsinterop-annotations

**Comment by niloc132** [comment]
I think this issue can be safely closed at this time.

That said, what is the difference between 2.1.0 and 2.0.2? Ostensibly, 2.1.0 is "newer", going by the numbers, but 2.0.2 was released about a week after 2.1.0, and the source code [is exactly the same](https://github.com/google/jsinterop-annotations/compare/2.0.2...2.1.0) - as are the deployed jars. Was there intended to be a difference, and should docs point to 2.1.0 instead of 2.0.2?

**Comment by gkdn** [comment]
I don't see 2.1.0 release; I see a tag but probably was accidentally created. 
@mason-lgtm do you recall what happened here?

**Comment by gkdn** [comment]
Oh I see. There is a Maven release not Github. Found this in our notes:

```
Warning: 2023, Aug 4: The latest released version of `jsinterop-annotations` in
Maven is 2.1.0. However, it was created mistakenly and is identical to 2.0.2.
Next release should be 2.1.1+
```

**Comment by niloc132** [comment]
Thank you, will disregard.
